music.playSoundEffect(music.builtinSoundEffect(soundExpression.soaring), SoundExpressionPlayMode.InBackground)
basic.showString("INICIANDO O SISTEMA")
music.playSoundEffect(music.builtinSoundEffect(soundExpression.soaring), SoundExpressionPlayMode.InBackground)
basic.showString("...")
music.startMelody(music.builtInMelody(Melodies.Baddy), MelodyOptions.OnceInBackground)
basic.showIcon(IconNames.Ghost)
basic.pause(2000)
basic.showIcon(IconNames.Skull)
basic.pause(2000)
music.startMelody(music.builtInMelody(Melodies.Ringtone), MelodyOptions.OnceInBackground)
basic.showIcon(IconNames.House)
basic.showString("PRONTO")
basic.showString("" + (input.temperature()))
basic.forever(function () {
    basic.clearScreen()
    music.playSoundEffect(music.createSoundEffect(WaveShape.Noise, 3604, 2946, 145, 0, 714, SoundExpressionEffect.None, InterpolationCurve.Logarithmic), SoundExpressionPlayMode.InBackground)
    images.iconImage(IconNames.Square).showImage(0)
    images.iconImage(IconNames.SmallSquare).showImage(0)
    basic.pause(500)
    music.playSoundEffect(music.createSoundEffect(WaveShape.Noise, 3604, 2946, 145, 0, 714, SoundExpressionEffect.None, InterpolationCurve.Logarithmic), SoundExpressionPlayMode.InBackground)
    images.iconImage(IconNames.Diamond).showImage(0)
    images.iconImage(IconNames.SmallDiamond).showImage(0)
    basic.pause(500)
    music.playSoundEffect(music.createSoundEffect(WaveShape.Sine, 1161, 264, 194, 0, 733, SoundExpressionEffect.None, InterpolationCurve.Logarithmic), SoundExpressionPlayMode.InBackground)
    images.iconImage(IconNames.Skull).showImage(0)
    basic.pause(500)
    images.iconImage(IconNames.Ghost).showImage(0)
    basic.pause(500)
})
